//------------------------------------------------------------------------
// Copyright(c) 2024 Stratojets.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"FlaschenTaschen.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"FlaschenTaschen VST3 (64Bit)"
#else
#define stringFileDescription	"FlaschenTaschen VST3"
#endif
#define stringCompanyName		"Stratojets\0"
#define stringLegalCopyright	"Copyright(c) 2024 Stratojets."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
